# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyVoice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyVoice
  pod 'onnxruntime-training-objc', '~>1.16.0'

  target 'MyVoiceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyVoiceUITests' do
    # Pods for testing
  end

end
